# Generated by Django 6.1.1 on 2026-09-07 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("neighborhood", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("note", models.TextField(blank=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="1-5, or empty for a place I have not rated yet.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("wishlist", "Wishlist"), ("visited", "Visited")],
                        default="wishlist",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_visited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="places", to="places.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
