# Generated by Django 6.1.1 on 2026-09-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(db_collation="NOCASE", max_length=50, unique=True),
        ),
    ]
