# Generated by Django 6.1.1 on 2026-09-08 04:44

from django.db import migrations


def normalize_existing_place_text(apps, schema_editor):
    """Strip the free text on rows written before ``Place.save`` normalized it.

    Issue #23: ``Place.save`` now guarantees the free-text columns never hold
    a value Python would consider padded or blank, but a guarantee that only
    holds for rows written after it shipped is not a guarantee -- ``stats``
    would still print a blank breakdown row for a legacy tab-only
    neighborhood, and ``todo``/``surprise``'s ``--neighborhood`` filters would
    still miss a legacy padded one, until something happened to re-save it.

    The stripping is done in Python, not in SQL: SQLite's ``TRIM()`` removes
    ``U+0020`` and nothing else, which is precisely the bug this migration is
    cleaning up after. ``save()`` is unavailable on a historical model, so the
    normalization rule is re-stated here rather than imported -- importing
    from ``places.models`` would bind this migration to whatever that module
    looks like in the future, which is the one thing a migration must not do.
    """
    Place = apps.get_model("places", "Place")
    fields = ("name", "neighborhood", "address", "note")

    changed = []
    for place in Place.objects.all().iterator():
        dirty = False
        for field in fields:
            value = getattr(place, field)
            stripped = "" if value is None else str(value).strip()
            if stripped != value:
                setattr(place, field, stripped)
                dirty = True
        if dirty:
            changed.append(place)

    if changed:
        Place.objects.bulk_update(changed, fields)


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_alter_tag_name"),
    ]

    operations = [
        # Irreversible in the honest sense rather than the destructive one:
        # the whitespace that was stripped is not recorded anywhere, so there
        # is nothing to put back. A no-op reverse keeps `migrate places 0002`
        # working instead of refusing.
        migrations.RunPython(
            normalize_existing_place_text,
            migrations.RunPython.noop,
        ),
    ]
